import { Montserrat } from "next/font/google";
import "@/styles/globals.css";
import Marquee from "react-fast-marquee";
import NavBar from "@/components/page-layout/root-page/NavBar";
import Trending from "@/components/page-layout/root-page/Trending";
import Footer from "@/components/page-layout/root-page/Footer";
import ReduxStoreProvider from "@/providers/ReduxStoreProvider";
import PostDeal from "@/components/sub-components/navbar/PostDeal";
import DealModal from "@/components/page-layout/root-page/DealModal";
import OfferAndDiscountSlider from "@/components/page-layout/home-page/OfferAndDiscountSlider";
import Test from "@/components/page-layout/root-page/Test";
import ClientWrapper from "@/components/global-layout-components/ClientWrapper";
export const metadata = {
  title: "DealBondhu",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en" className={montserrat.variable}>
      <body className="font-sans">
        {/* redux store provider */}
        <ClientWrapper>
          <ReduxStoreProvider>
            {/* <Test></Test> */}
            <Marquee pauseOnHover className=" w-full h-8 bg-[#F5F7FA]">
              <p className=" mr-20  lg:mr-0 font-medium">
                DealBondhu is community-supported. We may get paid by brands for
                deals, including promoted items.
              </p>
            </Marquee>
            <NavBar></NavBar>
            <Trending></Trending>
            {children}

            <Footer></Footer>
            {/* <PostDeal></PostDeal> */}
            <DealModal></DealModal>
          </ReduxStoreProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
