import { Montserrat, Hind_Siliguri } from "next/font/google";
import "@/styles/globals.css";
import NavBar from "@/components/page-layout/root-page/NavBar";
import Footer from "@/components/page-layout/root-page/Footer";
import ReduxStoreProvider from "@/providers/ReduxStoreProvider";
import DealModal from "@/components/page-layout/root-page/DealModal";
import Test from "@/components/page-layout/root-page/Test";
import ClientWrapper from "@/components/global-layout-components/ClientWrapper";
import ToastProvider from "@/providers/ToastProvider";
import HeadingMarquee from "@/components/page-layout/root-page/HeadingMarquee";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import Category from "@/components/page-layout/root-page/Category";
import ToggleTheme from "@/components/sub-components/navbar/ToggleTheme";
import GlobalLanguageProvider from "@/context/GlobalLanguageProvider";
export const metadata = {
  title: "DealBondhu",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

const shiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  variable: "--font-shiliguri",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${montserrat.variable} ${shiliguri.variable}`}
    >
      <body className="font-sans">
        <NextAuthSessionProvider>
          <GlobalLanguageProvider>
            <ClientWrapper>
              <ReduxStoreProvider>
                <HeadingMarquee></HeadingMarquee>
                <NavBar></NavBar>
                <Category></Category>
                {children}
                <Footer></Footer>
                <DealModal></DealModal>
              </ReduxStoreProvider>
              <ToastProvider></ToastProvider>
              <ToggleTheme></ToggleTheme>
            </ClientWrapper>
          </GlobalLanguageProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
